### ISSUE TITLE
Determine linting strategy for docs

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs-next#41] opened 2020-01-27 06:44 UTC
## Summary

In order to address concerns brought up via https://github.com/vuejs/docs-next/pull/40, I've created this issue to track how we lint docs going forward in order to make everyone's life easier. This will also have the benefit of making contributors lives easier since we won't have to request them to make stylistic changes anymore.

## Example Problem

Prettier has styles that conflict with the Vue style guide (e.g., space before parentheses when defining functions) and @NataliaTepluhina brought up the idea of switching to ESLint.

**Comment by NataliaTepluhina** [comment] 2020-09-19 12:53
Closing as a duplicate of https://github.com/vuejs/docs-next/issues/233

**Closed by NataliaTepluhina** 2020-09-19 12:53 UTC
Labels: enhancement
