### ISSUE TITLE
hello,Errors in the process of using vue

### ISSUE THREAD

**Issue by CQCcq** [vuejs/docs-next#435] opened 2020-08-28 06:10 UTC
www.zhmxx.top
Code address:https://github.com/CQCcq/vue3.0beta.git

**Comment by bencodezen** [comment] 2020-08-31 14:26
Hi @CQCcq! Thanks for opening an issue. Unfortunately I'm not able to understand what the problem is and have to close it at this time. Feel free to re-open if you can better describe what issue you're having with the docs.

**Closed by bencodezen** 2020-08-31 14:26 UTC
