### ISSUE TITLE
update Vue3 SSR documentation

### ISSUE THREAD

**Issue by Alanscut** [vuejs/docs-next#784] opened 2021-01-07 01:41 UTC
### What problem does this feature solve?
I found that the SSR usage of Vue3 is very different from Vue2. However, the documentation still refers to the Vue2, which is outdated. Is there an official Vue3 SSR documentation?

### What does the proposed API look like?
A new SSR documentation fully adapted to vue3.

**Comment by NataliaTepluhina** [comment] 2021-01-07 14:46
Closing as a duplicate of https://github.com/vuejs/docs-next/issues/533

**Closed by NataliaTepluhina** 2021-01-07 14:46 UTC
