### ISSUE TITLE
incomplete documentation for createRenderer

### ISSUE THREAD

**Issue by telic** [vuejs/docs-next#577] opened 2020-09-30 17:53 UTC
The documentation of createRenderer does not include a summary of its purpose and does not describe its parameter object. What is `patchProp`? What are `…nodeOpts`?

Furthermore, the generic type parameters are confusingly described as "arguments" in the same way that formal parameters are described for other functions on this page.

**Comment by NataliaTepluhina** [comment] 2020-09-30 17:59
A duplicate of https://github.com/vuejs/docs-next/issues/116

**Closed by NataliaTepluhina** 2020-09-30 17:59 UTC
