### ISSUE TITLE
this.$parent.xxx

### ISSUE THREAD

**Issue by aclowner** [vuejs/docs-next#715] opened 2020-11-27 01:56 UTC
vue2: this.$parent.xxx
vue3: How to use the function of parent component?

**Comment by skirtles-code** [comment] 2020-11-27 07:34
It should be the same in Vue 3:

https://jsfiddle.net/skirtle/m0ng1cqf/

There was a conversation in #454 about documenting the removal of `$parent` but it appeared to be a misunderstanding, possibly caused by a bug. `$parent` still exists and it is documented in the API Reference.

I would note that the use of `$parent` to call a function is generally discouraged. Ideally you should use events or props instead.

I'm going to close this for now. If I've misunderstood and you believe there's a documentation problem then please provide more information and we can reopen this. If you think you've found a library bug then you'll need to open an issue against the [vue-next](https://github.com/vuejs/vue-next/issues) repository.

**Closed by skirtles-code** 2020-11-27 07:34 UTC
